todo list using react
boo-shehab/todo-list pull request #1
Opened 2022-12-06 10:44 UTC by boo-shehab

This branch is feature branch for to-do-list application
Setup react application
Setup linters configuration
Remove unnecessary files in react app
Added Components folder
Added some js files in components folder
Created Add functionality for to-do-list
Created Remove functionality for to-do-list
Created Edit functionality for to-do-list
Created Check functionality for to-do-list
Added local-storage
Used React Hooks
Setup React-Router
Added About Page
Changed Readme file
Added .gitignore file
Fixed all linters errors

2022-12-06 20:00 UTC, usamamaliq requested changes
@boo-shehab,

**Changes Required**

![14bo](https://user-images.githubusercontent.com/101483956/206009513-30746a7d-7eb8-451a-92a1-3c50470bf67c.gif)


Good Job implementing the project requirements. There are some changes that I have proposed. Kindly fix those to move on to the next project. 👍
 
**Note: The changes marked optional are optional.**

**HIGHLIGHTS**

-  Your project is professional
-  Your repo is professional

2022-12-06 20:00 UTC, usamamaliq commented on README.old.md
> +# todo-list
Kindly remove this readme file as it contains nothing.

2022-12-06 20:00 UTC, usamamaliq commented on README.md
> +
In my opinion, you should only follow the new template of the readme file and should remove the auto-generated readme description while creating react app.

2022-12-06 20:00 UTC, usamamaliq commented on src/components/TodoContainer.js
> +/* eslint-disable react/state-in-constructor */
Optional: I can see you have disabled ES-Linter a lot in multiple files. I know that you had less time to complete the application but try to fix the errors in your spare time as this is a clean code requirement.

2022-12-07 10:30 UTC, usamamaliq approved these changes
Hi @boo-shehab,

# Status: Approved ✔️ ✔️ ✔️

![7MyJ](https://user-images.githubusercontent.com/101483956/206154459-63ec851d-e3a5-4b56-a147-9e5a873f1750.gif)


## Top Highlight 💪🏻

React Installed ✔️
React App opens in the browser ✔️
No Linters errors✔️
New Readme Template Used ✔️

Good job implementing the requirements 👍 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

**Congratulations!** 🎉

2022-12-07 10:31 UTC, boo-shehab commented
thank you

2022-12-07 10:31 UTC, merged